---
- project:
    queue: kolla
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - ansible-role-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs
    check:
      jobs:
        - kolla-ansible-centos9s
        - kolla-ansible-debian
        - kolla-ansible-debian-podman
        - kolla-ansible-rocky9
        - kolla-ansible-rocky9-podman
        - kolla-ansible-ubuntu-jammy
        - kolla-ansible-ubuntu-jammy-podman
        - kolla-ansible-ubuntu-noble
        - kolla-ansible-ubuntu-noble-podman
        - kolla-ansible-rocky9-kvm
        - kolla-ansible-ubuntu-jammy-kvm
        - kolla-ansible-ubuntu-noble-kvm
        - kolla-ansible-rocky9-multinode-ipv6
        - kolla-ansible-ubuntu-multinode-ipv6
        - kolla-ansible-rocky9-bifrost
        - kolla-ansible-ubuntu-bifrost
        - kolla-ansible-rocky9-zun
        - kolla-ansible-ubuntu-jammy-zun
        - kolla-ansible-ubuntu-noble-zun
        - kolla-ansible-rocky9-swift
        - kolla-ansible-ubuntu-swift
        - kolla-ansible-rocky9-scenario-nfv
        - kolla-ansible-rocky9-magnum
        - kolla-ansible-ubuntu-jammy-magnum
        - kolla-ansible-ubuntu-noble-magnum
        - kolla-ansible-rocky9-octavia
        - kolla-ansible-ubuntu-jammy-octavia
        - kolla-ansible-ubuntu-noble-octavia
        - kolla-ansible-rocky9-masakari
        - kolla-ansible-ubuntu-jammy-masakari
        - kolla-ansible-ubuntu-noble-masakari
        - kolla-ansible-rocky9-ironic
        - kolla-ansible-debian-ironic
        - kolla-ansible-ubuntu-jammy-ironic
        - kolla-ansible-ubuntu-noble-ironic
        - kolla-ansible-rocky9-upgrade
        - kolla-ansible-debian-upgrade
        - kolla-ansible-ubuntu-jammy-upgrade
        - kolla-ansible-ubuntu-jammy-cells
        - kolla-ansible-rocky9-cells
        - kolla-ansible-rocky9-mariadb
        - kolla-ansible-ubuntu-jammy-mariadb
        - kolla-ansible-ubuntu-noble-mariadb
        - kolla-ansible-debian-ovn
        - kolla-ansible-rocky9-ovn
        - kolla-ansible-ubuntu-jammy-ovn
        - kolla-ansible-ubuntu-noble-ovn
        - kolla-ansible-debian-upgrade-ovn
        - kolla-ansible-rocky9-upgrade-ovn
        - kolla-ansible-ubuntu-jammy-upgrade-ovn
        - kolla-ansible-debian
        - kolla-ansible-rocky9-prometheus-opensearch
        - kolla-ansible-ubuntu-jammy-prometheus-opensearch
        - kolla-ansible-ubuntu-noble-prometheus-opensearch
        - kolla-ansible-rocky9-prometheus-opensearch-upgrade
        - kolla-ansible-ubuntu-jammy-prometheus-opensearch-upgrade
        - kolla-ansible-rocky9-venus
        - kolla-ansible-ubuntu-jammy-venus
        - kolla-ansible-ubuntu-noble-venus
        - kolla-ansible-rocky9-cephadm
        - kolla-ansible-ubuntu-jammy-cephadm
        - kolla-ansible-ubuntu-noble-cephadm
        - kolla-ansible-rocky9-upgrade-cephadm
        - kolla-ansible-ubuntu-jammy-upgrade-cephadm
        - kolla-ansible-rocky9-hashi-vault
        - kolla-ansible-rocky9-haproxy-fqdn
        - kolla-ansible-ubuntu-jammy-haproxy-fqdn
        - kolla-ansible-ubuntu-noble-haproxy-fqdn
        - kolla-ansible-ubuntu-jammy-lets-encrypt
        - kolla-ansible-ubuntu-noble-lets-encrypt
        - kolla-ansible-rocky9-lets-encrypt
        - kolla-ansible-ubuntu-jammy-skyline
        - kolla-ansible-ubuntu-noble-skyline
        - kolla-ansible-rocky9-skyline
        - kolla-ansible-ubuntu-jammy-skyline-sso
        - kolla-ansible-ubuntu-noble-skyline-sso
        - kolla-ansible-rocky9-skyline-sso
    check-arm64:
      jobs:
        - kolla-ansible-debian-aarch64
        - kolla-ansible-debian-aarch64-podman
        - kolla-ansible-debian-upgrade-aarch64
    gate:
      jobs:
        - kolla-ansible-debian
        - kolla-ansible-debian-upgrade
        - kolla-ansible-debian-podman
        - kolla-ansible-rocky9
        - kolla-ansible-rocky9-prometheus-opensearch
        - kolla-ansible-rocky9-prometheus-opensearch-upgrade
        - kolla-ansible-rocky9-upgrade
        - kolla-ansible-rocky9-podman
        - kolla-ansible-ubuntu-jammy
        - kolla-ansible-ubuntu-jammy-prometheus-opensearch
        - kolla-ansible-ubuntu-jammy-prometheus-opensearch-upgrade
        - kolla-ansible-ubuntu-jammy-upgrade
        - kolla-ansible-ubuntu-jammy-podman
    experimental:
      jobs:
        - kolla-ansible-rocky9-swift-upgrade
        - kolla-ansible-ubuntu-jammy-swift-upgrade
